### PR TITLE
include operator pending mode in python motion mappings (corrected)

### PR DESCRIPTION
**Pull request by OrenLeaffer**
This is an update of PR:2 that has the correct behavior for select mode.

### CODE REVIEW

**Comment by sullyj3** [comment]
Hmm, the bindings don't seem to be working correctly for me. In the following file:

```
class Foo(object):
    def __init__(self, a):
        self.a = a

    @property
    def bar(self):
        return "poop"

class Blergh():
    pass

f = Foo(1)
print(f.bar)

```

`]]`, `]m`, `[[`, and `[m` all seem to do the same thing as `^`, in both normal, visual, and operator pending. Are you getting the same thing?

**Comment by sullyj3** [comment]
I appreciate the idea behind the refactor, naming the regexes is much cleaner.

**Comment by sullyj3** [comment]
It seems like the bindings work when I paste the regexes back into the function call instead of breaking them out as variables, so it might be so sort of escaping issue? `:help magic` and `:help string` are potentially relevant.

**Comment by OrenLeaffer** [comment]
I thought I'd tested it, but turned out I hadn't and had the same problem. I updated the pull request (I think) with a version that I've actually tested now.

**Comment by sullyj3** [comment]
Looks good!

**Pull request merged**
